language: java

jdk:
  - openjdk8
  - openjdk9

stages:
  - test
  - name: release
    if: branch = master && type != pull_request

script: ./gradlew check javadoc

jobs:
  include:
    - stage: release
      install: true
      script: ./gradlew bintrayUpload -x test

addons:
  apt:
    packages:
      - perl

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/