language: java

jdk:
  - openjdk8
  - openjdk9

stages:
  - test
  - name: release
    if: branch = master && type != pull_request

script: ./gradlew check javadoc

jobs:
  include:
    - stage: release
      install: true
      script: ./gradlew bintrayUpload -x test

addons:
  apt:
    packages:
      - perl