dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk9

stages:
  - test
  - name: release
    if: branch = master && type != pull_request

install: skip
script: ./gradlew check javadoc

jobs:
  include:
    - stage: release
      install: skip
      script: ./gradlew bintrayUpload githubRelease
      jdk: oraclejdk8

addons:
  apt:
    packages:
      - perl

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/