language: java

install: true

before_install:
  - chmod +x gradlew

jdk:
  - oraclejdk8
  - oraclejdk9

stages:
  - test
  - name: snapshot
    if: branch = develop
  - name: release
    if: branch = master

jobs:
  include:
    - stage: snapshot
      script: ./gradlew artifactoryPublish -x test -Dsnapshot=true
    - stage: release
      script: ./gradlew bintrayUpload -x test
