language: java

jdk:
  - oraclejdk8
  - oraclejdk9

stages:
  - test
  - name: snapshot
    if: branch = develop
  - name: release
    if: branch = master

jobs:
  include:
    - stage: snapshot
      install: true
      script: ./gradlew artifactoryPublish -x test -Dsnapshot=true
    - stage: release
      install: true
      script: ./gradlew bintrayUpload -x test
