@startuml

(*)-right->"HttpClientCodec \n CombinedChannelDuplexHandler \n [MqttWebSocketsChannelInitializer.initChannel]" as HttpClientCodec
-right-> "HttpObjectAggregator \n ChannelInboundHandler \n [MqttWebSocketsChannelInitializer.initChannel]"
-right-> "wsProtocolHandler \n ChannelInboundHandler \n [MqttWebSocketsChannelInitializer.initChannel]"
-right-> "WebSocketFrameDecoder \n ChannelInboundHandler \n [WSClientHandshaker.finishHandshake]"
-right-> "WebSocketBinaryFrameDecoder \n ChannelInboundHandler \n [WSClientHandshaker.finishHandshake]"
-right-> "MqttDisconnectOnAuthHandler \n ChannelDuplexHandler \n [WebSocketClientProtocolHandlerOnHandshakeComplete.\nuserEventTriggered.HANDSHAKE_COMPLETE]" as MqttDisconnectOnAuthHandler
-right-> "MqttConnectHandler \n ChannelInboundHandler \n [WebSocketClientProtocolHandlerOnHandshakeComplete.\nuserEventTriggered.HANDSHAKE_COMPLETE]"
-right-> "MqttDisconnectHandler \n ChannelInboundHandler \n [WebSocketClientProtocolHandlerOnHandshakeComplete.\nuserEventTriggered.HANDSHAKE_COMPLETE]"
-right-> Application In
-down-> Application Out
-left-> MqttDisconnectOnAuthHandler
-down-> "MqttEncoder \n ChannelOutboundHandler \n [WebSocketClientProtocolHandlerOnHandshakeComplete.\nuserEventTriggered.HANDSHAKE_COMPLETE]"
-left-> "WebSocketBinaryFrameEncoder \n ChannelOutboundHandler \n [WebSocketClientProtocolHandlerOnHandshakeComplete.\nuserEventTriggered.HANDSHAKE_COMPLETE]"
--> "WebSocketEncoder \n ChannelOutboundHandler \n [WSClientHandshaker.handshake]"
-left-> HttpClientCodec

@enduml
